"""empty message

Revision ID: 7e34784fcee2
Revises: 80313db2eb66
Create Date: 2020-03-12 16:55:52.974430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e34784fcee2'
down_revision = '80313db2eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=88), nullable=True),
    sa.Column('lastname', sa.String(length=88), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('time_created', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles2')
    # ### end Alembic commands ###
