"""empty message

Revision ID: dbac0edc2c26
Revises: 8e7a1a22abdb
Create Date: 2020-03-11 06:04:36.991908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbac0edc2c26'
down_revision = '8e7a1a22abdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'filename')
    # ### end Alembic commands ###
